#!/usr/bin/perl

use strict ;
use warnings ;
use Getopt::Long ;

my $printversion = 1;
my $subfigdir = 'bw';

GetOptions( 
   'subfigdir=s'    => \$subfigdir,
   'printversion!'  => \$printversion,
   'help'           => sub { die "usage: mkparams [--printversion] [--subfigdir color]\n" ; },
) ;

my $pv = '';
if ( $printversion )
{
   $pv = "\\toggletrue{print-version}";
}

my $tt = '';
if ( 0 )
{
   # see classicthesis-config.tex for reasons that this can't easily be done anymore.
   $tt = "\\toggletrue{use-lettersize}";
}

#\\RequirePackage{ifthenelse}
print qq(
\\RequirePackage{etoolbox}

\\newtoggle{print-version}
$pv

\\newcommand{\\subfigdir}[0]{$subfigdir}

\\newtoggle{use-lettersize}% false
$tt
);
